### ISSUE TITLE
Is there a way to run mcpdft on top of an existing pyscf casscf calculation?

### ISSUE THREAD

**Issue by HehnLukas** [MatthewRHermes/mcpdft#2]
In the old version of your code, you could do:

```
from mrh.my_pyscf.mcpdft import mcpdft, otfnal
def run_MCPDFT_old(cas, xc, ft=False, grid=5):
    ks = UKS(cas.mol)
    ks.xc = xc
    ks.grids.level = grid
    if ft:
        ot = otfnal.ftransfnal(ks)
    else:
        ot = otfnal.transfnal(ks)
    E = mcpdft.kernel(cas, ot, root=0)
    return cas, E[0]
```

with cas being a pyscf casscf object. Is there any way to do this in the new version, without redoing the casscf calculation as a calculation including the mcpdft calculation like this:
`mc1 = mcpdft.CASSCF (mf, 'tPBE', 6, 8).run ()`

I know that you can take that line and then do 
`mc1.compute_pdft_energy_(otxc='ftPBE')`

but i guess I would just need a line of code to transform mc1 into an mcpdft cas object:
```
mc1 = mcscf.CASSCF(mf, nel, norb, ...)

# Line missing here:

mc2.compute_pdft_energy_(otxc='ftPBE')`
```

**Comment by MatthewRHermes** [comment]
Does
```mc2 = mcpdft.CASSCF (mc1, nel, norb, ...)```
do what you want? It's supposed to copy the MO coefficients and CI vectors when you pass an mcscf object to the constructor. This is used extensively in certain unit tests.

**Comment by HehnLukas** [comment]
Oh wow I am very sorry, that was actually quite obvious. I just wanted to avoid redoing the casscf calculation, but of course you dont actually have to call the kernel function... Thank you for your help!
